services:
  - type: web
    name: carefox-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    region: oregon
    runtime: python

